/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trunk;

import java.util.Calendar;
import java.text.SimpleDateFormat;
import java.util.*;
import java.time.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Notandi
 */
public class HotelsGUI extends javax.swing.JFrame {

	int checkIn;
	int checkOut;
	
    /**
     * Creates new form DayTripGUI
     */
    public HotelsGUI() {
        initComponents();
        jPanel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableDialog = new javax.swing.JOptionPane();
        SearchOptions = new javax.swing.JPanel();
        Sightseeing = new javax.swing.JCheckBox();
        Fishing = new javax.swing.JCheckBox();
        Hiking = new javax.swing.JCheckBox();
        Glacier = new javax.swing.JCheckBox();
        fromDate = new com.toedter.calendar.JDateChooser();
        toDate = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Search = new javax.swing.JButton();
        nrOfRooms = new JTextField();
        nr_of_rooms = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        myTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel search");

        SearchOptions.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Options"));
        SearchOptions.setToolTipText("Search Options");

        Sightseeing.setText("Sightseeing");

        Fishing.setText("Fishing");

        Hiking.setText("Hiking");

        Glacier.setText("Glacier Trips");

        jLabel1.setText("From :");

        jLabel2.setText("To :");

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

     //   myLocation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Any", "Reykjavik", "Sudurland", "Austurland","Nordurland", "Vesturland" }));

        nr_of_rooms.setText("Nr. of rooms :");

        javax.swing.GroupLayout SearchOptionsLayout = new javax.swing.GroupLayout(SearchOptions);
        SearchOptions.setLayout(SearchOptionsLayout);
        SearchOptionsLayout.setHorizontalGroup(
            SearchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchOptionsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(SearchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SearchOptionsLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(toDate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SearchOptionsLayout.createSequentialGroup()
                        .addComponent(nr_of_rooms, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(nrOfRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Search))))
            .addGroup(SearchOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Sightseeing)
                .addGap(18, 18, 18)
                .addGroup(SearchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SearchOptionsLayout.createSequentialGroup()
                        .addComponent(Fishing)
                        .addGap(18, 18, 18)
                        .addComponent(Hiking)
                        .addGap(18, 18, 18)
                        .addComponent(Glacier))))
        );
        SearchOptionsLayout.setVerticalGroup(
            SearchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sightseeing)
                    .addComponent(Fishing)
                    .addComponent(Hiking)
                    .addComponent(Glacier))
                .addGap(18, 18, 18)
                .addGroup(SearchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fromDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SearchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search)
                    .addComponent(nrOfRooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nr_of_rooms))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        myTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        myTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
					myTableMouseClicked(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
        jScrollPane1.setViewportView(myTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        jMenuItem1.setText("Halp, pls");
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public String buildSqlstring(boolean sightseeing, boolean fishing, boolean hiking, boolean glacier, String location, String fDate, String tDate) {
        String sqlstatement = new String();
        sqlstatement = "SELECT * FROM Trips WHERE (fromDate BETWEEN '"+ fDate + "' AND '" + tDate + "') AND location = '" + location + "'";
        int count = 0;
        
        if(sightseeing == true) {
            count++;
        }
        if(fishing == true) {
            count++;
        }
        if(hiking == true) {
            count++;
        }
        if(glacier == true) {
            count++;
        }
        

        //Special case location = "Any"
        if(location.equals("Any")) {
            sqlstatement = "SELECT * FROM Trips WHERE (fromDate BETWEEN '"+ fDate + "' AND '" + tDate + "')";
        }
        
        if(count == 1) {
            if(sightseeing == true) {
                sqlstatement = sqlstatement + "AND type = 'Sightseeing'";
            }
            if(fishing == true) {
                sqlstatement = sqlstatement + "AND type = 'Fishing'";
            }
            if(hiking == true) {
                sqlstatement = sqlstatement + "AND type = 'Hiking'";
            }
            if(glacier == true) {
                sqlstatement = sqlstatement + "AND type = 'Glacier'";
            }
        }
        
        if(count == 2) {
            if(sightseeing == true && fishing == true) {
                sqlstatement = sqlstatement + "AND (type = 'Sightseeing' OR type = 'Fishing')";
            }
            if(sightseeing == true && hiking == true) {
                sqlstatement = sqlstatement + "AND (type = 'Sightseeing' OR type = 'Hiking')";
            }
            if(sightseeing == true && glacier == true) {
                sqlstatement = sqlstatement + "AND (type = 'Sightseeing' OR type = 'Glacier')";
            }
            if(fishing == true && hiking == true) {
                sqlstatement = sqlstatement + "AND (type = 'Fishing' OR type = 'Hiking')";
            }
            if(fishing == true && glacier == true) {
                sqlstatement = sqlstatement + "AND (type = 'Fishing' OR type = 'Glacier')";
            }
            if(hiking == true && glacier == true) {
                sqlstatement = sqlstatement + "AND (type = 'Hiking' OR type = 'Glacier')";
            }
        }
        
        if(count == 3) {
            if(sightseeing == true && fishing == true && hiking == true) {
                sqlstatement = sqlstatement + "AND (type = 'Sightseeing' OR type = 'Fishing' OR type = 'Hiking')";
            }
            if(sightseeing == true && fishing == true && glacier == true) {
                sqlstatement = sqlstatement + "AND (type = 'Sightseeing' OR type = 'Fishing' OR type = 'Glacier')";
            }
            if(sightseeing == true && hiking == true && glacier == true) {
                sqlstatement = sqlstatement + "AND (type = 'Sightseeing' OR type = 'Hiking' OR type = 'Glacier')";
            }
            
            if(fishing == true && hiking == true && glacier == true) {
                sqlstatement = sqlstatement + "AND (type = 'Fishing' OR type = 'Hiking' OR type = 'Glacier')";
            }
        }
        
        if(count == 4) {
            if(sightseeing == true && fishing == true && hiking == true && glacier == true) {
                sqlstatement = sqlstatement + "AND (type = 'Sightseeing' OR type = 'Fishing' OR type = 'Hiking' OR type = 'Glacier')";
            }
        }
        
        System.out.println(count);

        return sqlstatement+";";
    }
    
    
    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
       // jTextField1.setText(Controller.getTripsFromDatabase());
//        System.out.println(compareDates());
//        System.out.println(compareDates2());
        
        
        int nrofrooms = Integer.parseInt(nrOfRooms.getText());;
        
        
        DateFormat df = new SimpleDateFormat("yyyyMMdd");
        checkIn = Integer.parseInt(df.format(fromDate.getDate()));
        checkOut = Integer.parseInt(df.format(toDate.getDate()));
        
        System.out.println(checkIn);
        System.out.println(checkOut);

        if(toDate == null) {
            JOptionPane.showMessageDialog(null, "You must choose a date to search", "Date choosing Error", JOptionPane.ERROR_MESSAGE);
        }
            
//        int count = 0;
//        if(sightseeing == true) {
//            count++;
//        }
//        if(fishing == true) {
//            count++;
//        }
//        if(hiking == true) {
//            count++;
//        }
//        if(glacier == true) {
//            count++;
//        }
//        if(nrOfRooms == null) {
//            JOptionPane.showMessageDialog(null, "You must choose the number of rooms to search for", "Type choosing Error", JOptionPane.ERROR_MESSAGE);
//        }
       

//        System.out.println(buildSqlstring(sightseeing, fishing, hiking, glacier, location, fDate,tDate));
        jPanel2.setVisible(true);
       
        try {
    		Connection conn = PostgresqlConnection.getConnection();
    		Statement stmt = conn.createStatement();
    		String sql;
    		
    		// Pt.1 of Finding the rooms available on the requested dates
    	    sql = "SELECT roomid "
    	    		+ "FROM occupied_room "
    	    		+ "WHERE ((check_in <= "+checkOut+" AND "+checkOut+" <= check_out) "
    	    		+ "OR (check_in <= "+checkIn+" AND "+checkIn+" < check_out) "
    	    		+ "OR ("+checkIn+" < check_in AND "+checkOut+" > check_out))";	
    	    
    	    // Pt.2 of Finding the rooms available on the requested dates
    	    String sql2 = "SELECT * FROM rooms GROUP BY roomid HAVING roomid NOT IN ("+sql+")";
    	   	    
    	    ResultSet rs = stmt.executeQuery(sql2);		// rs contains rooms that are available on the specified dates
            ResultSetMetaData rsmt = rs.getMetaData();
           
            int columns = rsmt.getColumnCount();
           
            DefaultTableModel dtm = new DefaultTableModel() {
                   @Override
                    public boolean isCellEditable(int row, int column) {
                    //all cells false
                    return false;
                    }
            };
           
            Vector column_name = new Vector();
            Vector data_rows = new Vector();
           
            column_name.addElement("Room ID");
            column_name.addElement("Hotel Name");
            column_name.addElement("Hotel ID");
            column_name.addElement("Room Type");
            column_name.addElement("Price");
            	
            dtm.setColumnIdentifiers(column_name);
            System.out.println(nrofrooms);
           
            int count = 0;
            while(rs.next()) {
                data_rows = new Vector();
                for(int j= 1; j <= columns; j++){
                	if(j == 2) 
                	{
                		Controller cont = new Controller();
                		Hotel hotel = cont.getHotel(Integer.parseInt(rs.getString(j)));
                		String hotelname = hotel.getName();
                		data_rows.addElement(hotelname);
                	}
                	if(j == 5) data_rows.addElement(rs.getString(2));
                	else data_rows.addElement(rs.getString(j));
               }
               dtm.addRow(data_rows);
            }
            myTable.setModel(dtm);
        }
        
            catch(Exception e){
                System.err.println(e.getClass().getName() + ": " + e.getMessage());
                System.exit(0);
            }
    }//GEN-LAST:event_SearchActionPerformed
    
    
    private void myTableMouseClicked(java.awt.event.MouseEvent evt) throws SQLException {//GEN-FIRST:event_myTableMouseClicked
        System.out.println(myTable.getSelectedRow());
        int row = myTable.getSelectedRow();
        int column = myTable.getColumnCount();
        String show[] = new String[20];
        
        
        for(int i = 0; i < column; i++) {
            String table_click = myTable.getModel().getValueAt(row, i).toString();
            show[i] = table_click;
            System.out.print(show[i]);
            
        }
        JTextField firstName = new JTextField();	// Textaboxi� til a� skrifa �
        JTextField lastName = new JTextField();

        final JComponent[] inputs = new JComponent[] {
                new JLabel("Do you wish to reserve a room at " + show[1] + "?"),
		new JLabel("Type in your first name"),
		firstName,
		new JLabel("Type in your last name"),
		lastName
        };
        JOptionPane.showConfirmDialog(null, inputs, "Reservations", JOptionPane.OK_CANCEL_OPTION);
        System.out.println("\nYou entered " +
		firstName.getText() + ", " +
		lastName.getText() );
        
        Controller cont = new Controller();
        Guest newguy = cont.createNewGuest(firstName.getText(), lastName.getText());
        int id = newguy.getGuestID();
        int hotelid = Integer.parseInt(show[2]);
        int roomid= Integer.parseInt(show[0]);
        cont.createReservation(hotelid, roomid, checkIn, checkOut, id);
            
        final JComponent [] info = new JComponent[] {
        		new JLabel("Dear " +firstName.getText()+ ". Your reservation to stay at " +show[1]+ " has been confirmed!" )
        };
        
        JOptionPane.showMessageDialog(null, info, "Reservation confirmed", JOptionPane.QUESTION_MESSAGE);
        
        jPanel2.setVisible(false);
}
    //GEN-LAST:event_myTableMouseClicked
 
    public boolean compareDates() {

        Date date1 = new Date();
        fromDate.setDate(date1);
        Date date2 = new Date();
        
        //date1 = fromDate.getDate(); er hægt að nota í staðinn fyrir setDate
        //en þá breytist dagsetningin í fromDate í current date
        return date1.after(date2);
   }
    public boolean compareDates2() {
        Date date1 = new Date();
        toDate.getDate();
        Date date2 = new Date();
        
        return date1.after(date2);
    }

  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelsGUI().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Fishing;
    private javax.swing.JCheckBox Glacier;
    private javax.swing.JCheckBox Hiking;
    private javax.swing.JButton Search;
    private javax.swing.JPanel SearchOptions;
    private javax.swing.JCheckBox Sightseeing;
    private com.toedter.calendar.JDateChooser fromDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nr_of_rooms;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private JTextField nrOfRooms;
    private javax.swing.JTable myTable;
    private javax.swing.JOptionPane tableDialog;
    private com.toedter.calendar.JDateChooser toDate;
    // End of variables declaration//GEN-END:variables

}